#if !canImport(ObjectiveC)
import XCTest

extension ComplexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComplexTests = [
        ("testAddingTwoComplexNumbers", testAddingTwoComplexNumbers),
        ("testComplexEquality", testComplexEquality),
        ("testMultiplyingTwoComplexNumbers", testMultiplyingTwoComplexNumbers),
        ("testSubtractingTwoComplexNumbers", testSubtractingTwoComplexNumbers),
        ("testThatItHasAConjugate", testThatItHasAConjugate),
        ("testThatItHasAnAbsoluteValue", testThatItHasAnAbsoluteValue),
        ("testThatItHasRealAndImaginaryParts", testThatItHasRealAndImaginaryParts),
    ]
}

extension VeryLongTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VeryLongTests = [
        ("testEquality", testEquality),
        ("testThatItCanBeCreatedFromAnInt", testThatItCanBeCreatedFromAnInt),
        ("testThatItCanBeCreatedFromAString", testThatItCanBeCreatedFromAString),
        ("testThatItCanBeNegative", testThatItCanBeNegative),
        ("testThatItCanBePositive", testThatItCanBePositive),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ComplexTests.__allTests__ComplexTests),
        testCase(VeryLongTests.__allTests__VeryLongTests),
    ]
}
#endif
